export const QUERY_KEYS = {
    'get-estate-lands': 'get-estate-land',
    'get-lands': 'get-lands',
    'get-houses': 'get-houses',
    'get-material': 'get-materials',
    'get-materialById': (id: number) => `get-material-by-id-${id}`,
    'get-property-by-id': (id: number) => `get-property-by-id=${id}`,
    getUserDetails: 'get-details',
    'get-wallet-balance': 'get-wallet-balance',
    'get-banks': 'get-banks',
    'get-nigerian-banks': 'get-nigerian-banks',
    'get-schedules': 'get-schedules',
    'get-schedule-by-id': (id: string) => `get-schedule-by-id-${id}`,
    'get-personal-profile': 'get-personal-profile',
    'get-company-profile': 'get-comany-profile',
    'get-next-of-kin': 'get-next-of-kin',
    'get-single-profile': 'get-single-profile',
    'get-addresses': 'get-addresses',
    'get-wishlist-items': 'get-wishlist-items',
    'get-wallet-transactions': 'get-wallet-transactions',
    'get-projects': 'get-projects',
    'get-project-by-id': 'get-project-by-id',
    'get-plots': (id: number) => `get-plots-${id}`,
    'get-all-transactions': 'get-all-tranactions',
    'get-reservations': 'get-reservations',
    'get-investment-plans': 'get-investment-plans',
    'get-uppdates': (type: 'ESP' | 'MAIN_APP') => `get-updates-${type}`,
}