export const companyTypeData = [
    { label: "Sole Proprietorship", value: "sole_proprietorship" },
    { label: "Partnership", value: "partnership" },
    { label: "Limited Liability Company (LLC)", value: "llc" },
    { label: "Corporation (C-Corp, S-Corp)", value: "corporation" },
    { label: "Cooperative", value: "cooperative" },
    { label: "Private Company", value: "private" },
    { label: "Public Company", value: "public" },
    { label: "Government-owned Company", value: "government_owned" },
    { label: "Small Business", value: "small" },
    { label: "Medium-sized Enterprise", value: "medium" },
    { label: "Large Corporation", value: "large" },
    { label: "Multinational Corporation", value: "multinational" },
    { label: "Manufacturing", value: "manufacturing" },
    { label: "Service", value: "service" },
    { label: "Retail", value: "retail" },
    { label: "Technology", value: "technology" },
    { label: "Financial", value: "financial" },
    { label: "Healthcare", value: "healthcare" },
    { label: "For-profit", value: "for_profit" },
    { label: "Non-profit", value: "non_profit" },
    { label: "Social Enterprise", value: "social_enterprise" },
    { label: "Brick-and-mortar", value: "brick_and_mortar" },
    { label: "E-commerce", value: "ecommerce" },
    { label: "Franchise", value: "franchise" },
    { label: "Startup", value: "startup" }
  ];